#! /usr/bin/env python
msg1 = r"""
     _                              _   _____            _     _  __      
    | | ___  _   _ _ __ _ __   __ _| | |  ___|__  _ __  | |   (_)/ _| ___ 
 _  | |/ _ \| | | | '__| '_ \ / _` | | | |_ / _ \| '__| | |   | | |_ / _ \
| |_| | (_) | |_| | |  | | | | (_| | | |  _| (_) | |    | |___| |  _|  __/
 \___/ \___/ \__,_|_|  |_| |_|\__,_|_| |_|  \___/|_|    |_____|_|_|  \___|

                          ┌────────┐
     Keep it Private      │YAML    │      ┌──────┐     Or Make it Public
                          │---     │      │      │
                          │Markdown│─────►│ HTML │
                          │        │      │      │
                          │        │      └──────┘
                          │--------│
                          │YAML    │      ┌──────┐
                          │---     │      │      │
                          │Markdown│─────►│ HTML │
                          │        │      │      │
                          │        │      └──────┘
                          │--------│              
                          │YAML    │      ┌──────┐
                          │---     │      │      │
                          │Markdown│─────►│ HTML │
                          │        │      │      │
                          │        │      └──────┘
                          └────────┘
"""

import shlex
import shutil
from os import system
from os import getuid
from sys import stdout
from time import sleep
from pwd import getpwuid
from pyfiglet import Figlet
from subprocess import Popen, PIPE
print(msg1)
sleep(1)

# Get Linux Username for portability between systems
USERNAME = getpwuid(getuid())[0]
GIT_EXE = "/usr/bin/git"
REPOS = f"/home/{USERNAME}/repos/"
JOURNAL = f"{REPOS}journal/"

# Files to edit
edit_files = [
    f"{JOURNAL}_drafts/journal.md",
    f"{JOURNAL}_code/journal",
    f"{JOURNAL}_code/chop.py",
    "/home/ubuntu/.config/nvim/init.vim",
]

# Places to put files after editing
copy_to_destination = {
    f"{JOURNAL}_code/journal": "/home/ubuntu/pyenv/bin/journal",
    "/home/ubuntu/.config/nvim/init.vim": f"{JOURNAL}_code/init.vim",
}

# Repos to push after editing
git_repos = [
    f"{REPOS}journal",
]


# Load function early so we can use it, pronto!
def fig(text, description=None, font="standard"):
    #  _____ _       _      _
    # |  ___(_) __ _| | ___| |_
    # | |_  | |/ _` | |/ _ \ __|
    # |  _| | | (_| | |  __/ |_
    # |_|   |_|\__, |_|\___|\__|
    #          |___/
    """Let them see text!"""
    f = Figlet(font=font)
    print(f.renderText(text))
    if description:
        print(description)
    sleep(0.5)


def flush(std):
    """Flush a stream."""
    for line in std:
        line = line.strip()
        if line:
            print(line)
            stdout.flush()


def git(cwd, line_command):
    #        _ _
    #   __ _(_) |_   This is it. This is git.
    #  / _` | | __|  It does the simple deed.
    # | (_| | | |_   From a shell what it does well
    #  \__, |_|\__|  Is move things where you need.
    #  |___/
    """Run a Linux git command."""
    cmd = [GIT_EXE] + shlex.split(line_command)
    show_cmd = " ".join(cmd)
    print(f"Running: {show_cmd}")
    process = Popen(
        args=cmd,
        cwd=cwd,
        stdout=PIPE,
        stderr=PIPE,
        shell=False,
        bufsize=1,
        universal_newlines=True,
    )
    flush(process.stdout)


def git_pull():
    for arepo in git_repos:
        fig(f"{arepo.split('/')[-1]}", font="cybermedium")
        git(arepo, "pull")
        print()


def load_editor():
    files = " ".join(edit_files)
    command = f"cd {JOURNAL}; nvim {files}"
    system(command)


def git_push():
    for repo in git_repos:
        fig(f"{repo.split('/')[-1]}", font="cybermedium")
        print(f"Pushing {repo} to Github...")
        git(repo, "commit -am 'pushing to github...'")
        git(repo, "push")
        print()


def copy_files():
    for source, destination in copy_to_destination.items():
        print(f"Copying {source} to {destination}")
        shutil.copyfile(source, destination)


def reverse_copy():
    for destination, source in copy_to_destination.items():
        print(f"Copying {source} to {destination}")
        destination = "/".join(destination.split("/")[:-1])
        shutil.copy(source, destination)


# Main Control Flow
fig("git pulls...")
git_pull()
reverse_copy()
fig("Loading Editor...")
load_editor()
print("Editor Loaded with multiple buffers.")
fig("Quitting Editor...")
copy_files()
fig("git pushes...")
git_push()
fig("Done!", "All done. Have a nice day!")
